#!/bin/sh

set -e

echo "Blablablablablablablablablablablablablabla" > bla.file
cp bla.file bla.file.orig
gzip bla.file
gzip -l bla.file.gz
gunzip bla.file.gz
cmp bla.file bla.file.orig
rm bla.file bla.file.orig
